// Date: 8/11/2013 9:45:13 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package awesomemancam.minersdeluxe.mob.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelCaveSnake extends ModelBase
{
	//fields
	ModelRenderer bodyLower;
	ModelRenderer tail;
	ModelRenderer bodyUpper;
	ModelRenderer neck;
	ModelRenderer head;

	public ModelCaveSnake()
	{
		textureWidth = 64;
		textureHeight = 32;

		bodyLower = new ModelRenderer(this, 0, 0);
		bodyLower.addBox(-1F, 0F, -3F, 2, 2, 6);
		bodyLower.setRotationPoint(0F, 22F, 2F);
		bodyLower.setTextureSize(64, 32);
		bodyLower.mirror = true;
		setRotation(bodyLower, 0F, 0.418879F, 0F);
		tail = new ModelRenderer(this, 2, 2);
		tail.addBox(-1F, 0F, -4F, 2, 2, 4);
		tail.setRotationPoint(0F, 22F, 8F);
		tail.setTextureSize(64, 32);
		tail.mirror = true;
		setRotation(tail, 0F, -0.2792527F, 0F);
		bodyUpper = new ModelRenderer(this, 2, 2);
		bodyUpper.addBox(-1F, 0F, 0F, 2, 2, 4);
		bodyUpper.setRotationPoint(0F, 22F, -4F);
		bodyUpper.setTextureSize(64, 32);
		bodyUpper.mirror = true;
		setRotation(bodyUpper, 0F, -0.2792527F, 0F);
		neck = new ModelRenderer(this, 2, 2);
		neck.addBox(-1F, -2F, -4F, 2, 2, 4);
		neck.setRotationPoint(0F, 24F, -4F);
		neck.setTextureSize(64, 32);
		neck.mirror = true;
		setRotation(neck, -1.047198F, 0F, 0F);
		head = new ModelRenderer(this, 16, 3);
		head.addBox(-1F, -2F, -2F, 2, 2, 3);
		head.setRotationPoint(0F, 21F, -5F);
		head.setTextureSize(64, 32);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		bodyLower.render(f5);
		tail.render(f5);
		bodyUpper.render(f5);
		neck.render(f5);
		head.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f1, float f2, float f3, float f4, float f5, float f6, Entity entity)
	{
		this.head.rotateAngleX = f5 / (170F / (float)Math.PI);
		this.head.rotateAngleY = f4 / (180F / (float)Math.PI);
	}

}
